# Generated by Django 5.0.6 on 2024-07-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='captcha',
        ),
    ]
