# Generated by Django 5.0.6 on 2024-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='team_pics/'),
        ),
    ]
