# Generated by Django 5.0.6 on 2024-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0002_alter_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
