# Generated by Django 5.0.6 on 2024-06-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room_type', models.CharField(max_length=50)),
                ('special_requests', models.TextField(blank=True)),
            ],
        ),
    ]
