# Generated by Django 5.0.6 on 2024-06-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0003_alter_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='team_pics/'),
        ),
    ]
