# Generated by Django 5.0.6 on 2024-06-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0004_alter_team_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
