# Generated by Django 5.0.6 on 2024-06-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0005_booking_price_alter_booking_special_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
    ]
