# Generated by Django 5.0.6 on 2024-06-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0007_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
    ]
