# Generated by Django 5.0.6 on 2024-06-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0009_alter_room_options_booking_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
    ]
