# Generated by Django 5.0.6 on 2024-06-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0013_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='captcha',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
