# Generated by Django 5.0.6 on 2024-06-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0014_booking_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='captcha',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
    ]
