# Generated by Django 5.0.6 on 2024-07-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kays', '0008_rename_room_type_booking_surname_and_more'),
        ('kays', '0015_remove_booking_captcha_remove_booking_price'),
    ]

    operations = [
    ]
